# Generated by Django 5.1.2 on 2024-10-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
